### PR TITLE
Update: nav and author profile

### PR DESCRIPTION
**Pull request by rakesh-gupta29**
## Update: schema for Nav and Author
- Added links for author and tags
- Added Author profile
- Removed date from author partial due to repetition.
- Fixed some margins and styling for smaller screens.

### Reference screenshots
image
image
image

> I am just learning HUGO and thought of working on some real project. Please let me know in case I need to make some other changes.

### CODE REVIEW

**Comment by mr-karan** [comment]
@rakesh-gupta29 Can you rebase

**Comment by mr-karan** [comment]
@rakesh-gupta29 Is this ready for review?

**Comment by rakesh-gupta29** [comment]
@mr-karan Sorry for the delay, Karan. Yes, you can review this.

**Comment by rakesh-gupta29** [comment]
@mr-karan I have updated the code as per latest changes in design. Please review.

**Comment by blacksof-dev** [comment]
@mr-karan @knadh

**Comment by blacksof-dev** [comment]
@mr-karan @knadh Please review this. Moreover, I have fixed some styles for tags and authors page too.
ss attached for reference:
image

**Comment by rakesh-gupta29** [comment]
@mr-karan

**Comment by rakesh-blacksof** [comment]
@mr-karan Please review the PR. Do I need to make any further changes.

**Comment by mr-karan** [comment]
@rakesh-blacksof Unfortunately I've to close this PR as this cannot be merged. The design language isn't in-line with our theme and currently we don't feel the need to add additional links and sections.

Apologies for the same but thanks a lot for showing your interests and contributing to the blog, really appreciate it.

**Pull request closed without merging**
